...
name: Cypress Tests
  on: [push]
jobs:
  cypress-run:
     runs on: ubuntu-latest
     steps: 
      -name: checkout
       uses: actions/checkout@v2.3.4      
      -name: cypress.io
       uses: cypress.io/github-action@v2.9.7
       with:
         build: npm run build
         start: npm start
       
  
