name: Cypress Tests
on: [push]
jobs:
  cypress-run:
     runs-on: ubuntu-latest
     steps: 
       - name: Checkout
         uses: actions/checkout@v4     
       - name: cypress.io
         uses: cypress-io/github-action@v6
         with:
           start: npm start
          
       
  
